apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: easytax-platform
  name: easytax-platform
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: easytax-platform
  type: LoadBalancer
status:
  loadBalancer: {}
