apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-simple
  name: postgres-simple
spec:
  ports:
    - port: 5432
      nodePort: 30036
      name: http
  selector:
    app: postgres-simple
  type: NodePort
status:
  loadBalancer: {}

