apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-web-postgres-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/hsts: "false"
spec:
  rules:
    - http:
        paths:
        -  path: /
           backend:
              serviceName: simple-web-postgres-cluster-ip
              servicePort: 80
