{{- if and .Values.secrets.create .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: web-tls-secret
  labels:
    app: {{ template "simple-web-postgres.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.webTlsCert | b64enc | quote }}
  tls.key: {{ .Values.secrets.webTlsKey | b64enc | quote }}
{{- end }}

