apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "simple-web-postgres.fullname" . }}
  name: {{ include "simple-web-postgres.fullname" . }}
spec:
  selector:
    app: {{ include "simple-web-postgres.fullname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.web.port }}